# Python is required for the deploy script
language: python
python:
- '3.5'

# The Sass part is the actual build
install:
- rvm install 2.4.1
# - gem install sass
- pip install -r .update/requirements.txt
script:
- echo "Nothing to do, we're not actually compiling sass"
deploy:
  provider: script
  script: python .update/updateSubreddit.py
  skip_cleanup: true
  on:
    branch: master
